#!/bin/bash

clear
stsbot=$(ps x | grep "terminus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")

figlet   '  BOT ZAP' | lolcat
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -e "  \033[1;31m\033[1;34m[\033[1;37m01\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR BOT ZAP \033[0m"
    echo -e "  \033[1;31m\033[1;34m[\033[1;37m02\033[1;34m]\033[1;37m ➩  \033[1;33mABRIR MENU DO BOT\033[0m"
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -e "  \033[1;31m\033[1;34m[\033[1;37m00\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR AO MENU PRINCIPAL \033[0m"
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -ne "\033[1;31m╚╣\033[1;32m INFORME UMA OPÇÃO \033[1;37m: "; read x

   case "$x" in

      1 | 01)
          clear
         wget https://vip.cxvpn.com.br/TBot.zip && unzip TBot.zip && cd TBotPlus; chmod +x TerminusBot.sh && ./TerminusBot.sh; cd; wget -qO- raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash && source ~/.profile && nvm install 16 && nvm use 16; botzap
         ;;

      2 | 02)
         clear
         terminus
         ;;
         
      0 | 00)
         menu
         ;;

      *)
         echo "opcao invalida, tente de novo"
         ;;

   esac
.bot
